--- 
clone: 
  depth: 1
kind: pipeline
name: NRXHKernel
steps: 
  - 
    commands:
      - "apt-get install -y bc libssl-dev libelf-dev bison"
      - "git clone https://github.com/xealea/xea-linux-laptop-x86 --depth=1"
      - "cd xea-linux-laptop-x86"
      - "curl -s https://raw.githubusercontent.com/xealea/builder-kernel-x86/clang/tarzstpkg | bash"
    image: silkeh/clang:latest
    name: clang-16
    trigger: 
      branch: 
        - master
